const fs = require('fs');
const path = require('path');

const LEADS_FILE = path.join(__dirname, '../../leads.json');
const SUMMARY_FILE = path.join(__dirname, '../../SUMMARY.md');

function generateSummary() {
  console.log('[AUTOMATON] Generating project summary & analytics...');
  
  if (!fs.existsSync(LEADS_FILE)) {
    console.log('[ERROR] No leads database found.');
    return;
  }

  const leads = JSON.parse(fs.readFileSync(LEADS_FILE, 'utf8'));
  
  const totalLeads = leads.length;
  const pitchedLeads = leads.filter(l => l.status === 'Pitch Generated').length;
  const newLeads = leads.filter(l => l.status === 'New').length;

  let summaryContent = `# 🍋 Mr. Lemon (Automaton) - System Summary\n\n`;
  summaryContent += `**Last Updated:** ${new Date().toLocaleString()}\n\n`;
  summaryContent += `## 📊 Pipeline Metrics\n`;
  summaryContent += `- **Total Active Leads:** ${totalLeads}\n`;
  summaryContent += `- **Pitches Auto-Generated:** ${pitchedLeads}\n`;
  summaryContent += `- **Pending Leads:** ${newLeads}\n\n`;

  summaryContent += `## 🎯 Target Pipeline Details\n\n`;
  summaryContent += `| ID | Client Name | Email | Status | Deal Value |\n`;
  summaryContent += `|---|---|---|---|---|\n`;

  leads.forEach(l => {
    summaryContent += `| ${l.id} | ${l.client} | ${l.email} | **${l.status}** | ${l.value} |\n`;
  });

  summaryContent += `\n\n---\n*Automated 24/7 Report generated by Mr. Lemon System Engine.*`;

  fs.writeFileSync(SUMMARY_FILE, summaryContent);
  console.log('[AUTOMATON] SUMMARY.md successfully generated and updated!');
}

generateSummary();
